### ISSUE TITLE
Carbon Labs: React Support

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-labs#262]
In order to allow for early experimentation/innovation, we should allow for the creation of React components in Carbon Labs. This work at a high level should consider:

- Potentially have two workspace folders to separate between web components and react experiments
- Blend web components and react in a single Storybook instance, and separate into categories in the Storybook left navigation between "Web Components (framework agnostic)" and "React components".
- Boilerplate React component for contributors to have a starting point

The ideal state is that when a component becomes more mature, the ability to migrate to a place like Carbon React would be a simple copy/paste. This would mean that the way the components are structured and built so emulate how they are ultimately built in Carbon React proper.

Similarly, this would be a continued consideration between Carbon Labs web components and Carbon Web Components to be able to copy/paste seamlessly when components are graduated.

This would be an initiative that would greatly help alleviate the intake of novel components before they become stable and graduate to Carbon for IBM Products.

Repository: https://github.com/carbon-design-system/carbon-labs

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/273
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/265
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/263
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/264
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/323
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/330
```
