### ISSUE TITLE
Carbon Labs: Update existing folder structure to separate web components and react components, add required dependencies to match `@carbon/react`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-labs#273]
Add React support for lab components. The infrastructure should mirror `@carbon/react` as much as possible to facilitate graduation, if/when a component moves from one repo to another.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/287
- [ ] Initialize Storybook (example story, build, etc)
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/285
- [ ] https://github.com/carbon-design-system/carbon-labs/issues/286
```
